reg delete HKCU\Software\Microsoft\Windows\CurrentVersion\Policies /f 
reg delete HKCU\Software\Microsoft\WindowsSelfHost /f 
reg delete HKCU\Software\Policies /f 
reg delete HKLM\Software\Microsoft\Policies /f 
reg delete HKLM\Software\Microsoft\Windows\CurrentVersion\Policies /f 
reg delete HKLM\Software\Microsoft\Windows\CurrentVersion\WindowsStore\WindowsUpdate /f 
reg delete HKLM\Software\Microsoft\WindowsSelfHost /f 
reg delete HKLM\Software\Policies /f 
reg delete HKLM\Software\WOW6432Node\Microsoft\Policies /f 
reg delete HKLM\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Policies /f 
reg delete HKLM\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\WindowsStore\WindowsUpdate /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot /f
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU /f
