@echo off
TITLE Slim down Firefox
CLS

fsutil dirty query %systemdrive% >nul 2>&1
if ERRORLEVEL 1 (
 ECHO.
 ECHO =============================================
 ECHO This script needs Administrator permissions!
 ECHO.
 ECHO Please run it as the Administrator.
 ECHO =============================================
 ECHO.
 PAUSE >NUL
 goto end
)

ECHO.

ECHO This script will clear everything except bookmarks and passwords
ECHO in your Firefox profile.
ECHO.
ECHO Especially: settings, cache, history, cookies, extensions
ECHO and extensions data will be CLEARED!
ECHO.
ECHO.
ECHO Type YES if your are sure, that you want to continue.
ECHO Otherwise, the script will do nothing.
ECHO.
set /p CONT=Do you want to continue?

if "%CONT%"=="YES" goto DOSLIMFF
if "%CONT%"=="yes" goto DOSLIMFF
if "%CONT%"=="Yes" goto DOSLIMFF
if "%CONT%"=="YEs" goto DOSLIMFF
if "%CONT%"=="yEs" goto DOSLIMFF
if "%CONT%"=="yES" goto DOSLIMFF
if "%CONT%"=="YeS" goto DOSLIMFF
set CONT=
ECHO.
ECHO Cancelling!
ECHO.
ECHO Press any key to exit the script.
ECHO.
PAUSE >NUL
goto end
:DOSLIMFF
set CONT=

ECHO.
ECHO.

if not exist "%APPDATA%\Mozilla\Firefox\installs.ini" goto FFnotinstalled
if not exist "%APPDATA%\Mozilla\Firefox\Profiles\*" goto FFnotinstalled
goto FFinstalled
:FFnotinstalled
 ECHO.
 ECHO ==================================================
 ECHO Firefox is not properly set up.
 ECHO.
 ECHO Please install Firefox, run it and then close it.
 ECHO ==================================================
 ECHO.
 PAUSE >NUL
 goto end
:FFinstalled

tasklist | findstr /i /l /c:"firefox.exe" >nul 2>&1 || goto noFFrunning
 ECHO.
 ECHO =============================================
 ECHO Firefox is running.
 ECHO.
 ECHO Please close Firefox and try again.
 ECHO =============================================
 ECHO.
 PAUSE >NUL
 goto end
:noFFrunning

ECHO Clearing cache...
rd /s /q "%LOCALAPPDATA%\Mozilla\Firefox" >nul 2>&1
rd /s /q "%APPDATA%\Mozilla\Firefox\Crash Reports" >nul 2>&1
rd /s /q "%APPDATA%\Mozilla\Firefox\Pending Pings" >nul 2>&1

ECHO Setting up Firefox...
for /f "delims=" %%i in ('dir /a /s /b "%APPDATA%\Mozilla\Firefox\Profiles\prefs.js" 2^>nul') do (
 mkdir "%TEMP%\SlimFirefox" >nul 2>&1
 copy /b /y "%%~dpiplaces.sqlite" "%TEMP%\Firefox" >nul 2>&1
 copy /b /y "%%~dpilogins.json" "%TEMP%\Firefox" >nul 2>&1
 copy /b /y "%%~dpikey4.db" "%TEMP%\Firefox" >nul 2>&1
 rd /s /q "%%~dpi" >nul 2>&1
 mkdir "%%~dpi" >nul 2>&1 
 copy /b /y "%TEMP%\Firefox\places.sqlite" "%%~dpi" >nul 2>&1
 copy /b /y "%TEMP%\Firefox\logins.json" "%%~dpi" >nul 2>&1
 copy /b /y "%TEMP%\Firefox\key4.db" "%%~dpi" >nul 2>&1
 rd /s /q "%TEMP%\Firefox" >nul 2>&1
 call :create_prefs %%~dpiprefs.js
 mkdir "%%~dpichrome"
 call :create_userChrome %%~dpichrome\userChrome.css
)

ECHO.
ECHO Done!
ECHO.
PAUSE

:end
exit

:create_prefs
 echo # Mozilla User Preferences>"%1"
 echo.>>"%1"
 echo /* Do not edit this file.>>"%1"
 echo  *>>"%1"
 echo  * If you make changes to this file while the application is running,>>"%1"
 echo  * the changes will be overwritten when the application exits.>>"%1"
 echo  *>>"%1"
 echo  * To make a manual change to preferences, you can visit the URL about:config>>"%1"
 echo  */>>"%1"
 echo.>>"%1"

 echo user_pref("app.feedback.baseURL", "");>>"%1"
 echo user_pref("app.support.baseURL", "");>>"%1"
 echo user_pref("app.normandy.enabled", false);>>"%1"
 echo user_pref("app.normandy.api_url", "");>>"%1"
 echo user_pref("app.normandy.shieldLearnMoreUrl", "");>>"%1"
 echo user_pref("app.releaseNotesURL", "");>>"%1"
 echo user_pref("app.releaseNotesURL.aboutDialog", "");>>"%1"
 echo user_pref("app.releaseNotesURL.prompt", "");>>"%1"
 echo user_pref("app.support.baseURL", "");>>"%1"
 echo user_pref("app.update.url.details", "");>>"%1"
 echo user_pref("app.update.url.manual", "");>>"%1"
 echo user_pref("accessibility.force_disabled", 1);>>"%1"
 echo user_pref("browser.uitour.url", "");>>"%1"
 echo user_pref("browser.xr.warning.infoURL", "");>>"%1"
 echo user_pref("browser.sessionstore.max_tabs_undo", 0);>>"%1"
 echo user_pref("browser.cache.disk.capacity", 0);>>"%1"
 echo user_pref("browser.cache.disk.enable", false);>>"%1"
 echo user_pref("browser.cache.memory.enable", false);>>"%1"
 echo user_pref("browser.cache.disk_cache_ssl", false);>>"%1"
 echo user_pref("browser.cache.disk.smart_size.enabled", false);>>"%1"
 echo user_pref("browser.geolocation.warning.infoURL", "");>>"%1"
 echo user_pref("browser.formfill.enable", false);>>"%1"
 echo user_pref("browser.compactmode.show", true);>>"%1"
 echo user_pref("browser.download.useDownloadDir", false);>>"%1"
 echo user_pref("browser.aboutConfig.showWarning", false);>>"%1"
 echo user_pref("browser.urlbar.showSearchSuggestionsFirst", false);>>"%1"
 echo user_pref("browser.bookmarks.restore_default_bookmarks", false);>>"%1"
 echo user_pref("browser.contentblocking.report.lockwise.enabled", false);>>"%1"
 echo user_pref("browser.contentblocking.report.cookie.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.cryptominer.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.fingerprinter.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.lockwise.how_it_works.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.manage_devices.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.mobile-android.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.mobile-ios.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.monitor.how_it_works.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.monitor.sign_in_url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.monitor.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.proxy_extension.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.social.url", "");>>"%1"
 echo user_pref("browser.contentblocking.report.tracker.url", "");>>"%1"
 echo user_pref("browser.safebrowsing.downloads.enabled", false);>>"%1"
 echo user_pref("browser.safebrowsing.downloads.remote.block_dangerous", false);>>"%1"
 echo user_pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false);>>"%1"
 echo user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);>>"%1"
 echo user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);>>"%1"
 echo user_pref("browser.safebrowsing.downloads.remote.enabled", false);>>"%1"
 echo user_pref("browser.safebrowsing.downloads.remote.url", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google.advisoryURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google.gethashURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google.reportMalwareMistakeURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google.reportPhishMistakeURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google.reportURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google.updateURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google4.advisoryURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google4.gethashURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google4.reportMalwareMistakeURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google4.reportPhishMistakeURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google4.reportURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google4.updateURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.mozilla.gethashURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.reportPhishURL", "");>>"%1"
 echo user_pref("browser.safebrowsing.allowOverride", false);>>"%1"
 echo user_pref("browser.safebrowsing.blockedURIs.enabled", false);>>"%1"
 echo user_pref("browser.safebrowsing.downloads.remote.timeout_ms", 0);>>"%1"
 echo user_pref("browser.safebrowsing.prefixset_max_array_size", 0);>>"%1"
 echo user_pref("browser.safebrowsing.id", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google.advisoryName", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google.lists", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google.pver", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google4.advisoryName", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google4.lists", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.google4.pver", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.mozilla.lists", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.mozilla.lists.base", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.mozilla.lists.content", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "");>>"%1"
 echo user_pref("browser.safebrowsing.provider.mozilla.pver", "");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.asrouter.useRemoteL10n", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.default.sites", "");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.discoverystream.enabled", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.discoverystream.endpointSpocsClear", "");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.discoverystream.endpoints", "");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.discoverystream.spocs.personalized", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.feeds.aboutpreferences", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.feeds.sections", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.options", "");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.feeds.system.topsites", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.feeds.systemtick", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.feeds.places", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.feeds.favicon", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.feeds.discoverystreamfeed", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.fxaccounts.endpoint", "");>>"%1"              
 echo user_pref("browser.newtabpage.activity-stream.improvesearch.noDefaultSearchTile", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.showSponsored", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.telemetry", false);>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.telemetry.structuredIngestion.endpoint", "");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.asrouter.providers.cfr", "{\"id\":\"cfr\",\"enabled\":false,\"type\":\"remote-settings\",\"bucket\":\"cfr\",\"updateCycleInMs\":3600000}");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.asrouter.providers.cfr-fxa", "{\"id\":\"cfr-fxa\",\"enabled\":false,\"type\":\"remote-settings\",\"bucket\":\"cfr-fxa\",\"updateCycleInMs\":3600000}");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.asrouter.providers.message-groups", "{\"id\":\"message-groups\",\"enabled\":false,\"type\":\"remote-settings\",\"bucket\":\"message-groups\",\"updateCycleInMs\":3600000}");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.asrouter.providers.messaging-experiments", "{\"id\":\"messaging-experiments\",\"enabled\":false,\"type\":\"remote-experiments\",\"messageGroups\":[\"cfr\",\"whats-new-panel\",\"moments-page\",\"snippets\",\"cfr-fxa\",\"aboutwelcome\"],\"updateCycleInMs\":3600000}");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.asrouter.providers.onboarding", "{\"id\":\"onboarding\",\"type\":\"local\",\"localProvider\":\"OnboardingMessageProvider\",\"enabled\":false,\"exclude\":[]}");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.asrouter.providers.snippets", "{\"id\":\"snippets\",\"enabled\":false,\"type\":\"remote\",\"url\":\"https://snippets.cdn.mozilla.net/%%STARTPAGE_VERSION%%/%%NAME%%/%%VERSION%%/%%APPBUILDID%%/%%BUILD_TARGET%%/%%LOCALE%%/%%CHANNEL%%/%%OS_VERSION%%/%%DISTRIBUTION%%/%%DISTRIBUTION_VERSION%%/\",\"updateCycleInMs\":14400000}");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.asrouter.providers.whats-new-panel", "{\"id\":\"whats-new-panel\",\"enabled\":false,\"type\":\"remote-settings\",\"bucket\":\"whats-new-panel\",\"updateCycleInMs\":3600000}");>>"%1"
 echo user_pref("browser.newtabpage.activity-stream.discoverystream.config", "{\"api_key_pref\":\"extensions.pocket.oAuthConsumerKey\",\"collapsible\":true,\"enabled\":false,\"show_spocs\":false,\"hardcoded_layout\":true,\"personalized\":true,\"layout_endpoint\":\"https://getpocket.cdn.mozilla.net/v3/newtab/layout?version=1^&consumer_key=$apiKey^&layout_variant=basic\"}");>>"%1"
 echo user_pref("browser.urlbar.speculativeConnect.enabled", false);>>"%1"
 echo user_pref("browser.urlbar.suggest.engines", false);>>"%1"
 echo user_pref("browser.urlbar.suggest.topsites", false);>>"%1"
 echo user_pref("browser.formfill.expire_days", 0);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.urlbar.suggest.engines", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.urlbar.suggest.topsites", false);>>"%1"
 echo user_pref("dom.battery.enabled", false);>>"%1"
 echo user_pref("dom.event.clipboardevents.enabled", false);>>"%1"
 echo user_pref("dom.event.contextmenu.enabled", false);>>"%1"
 echo user_pref("dom.push.connection.enabled", false);>>"%1"
 echo user_pref("dom.push.enabled", false);>>"%1"
 echo user_pref("dom.push.serverURL", "");>>"%1"
 echo user_pref("dom.webnotifications.enabled", false);>>"%1"
 echo user_pref("dom.gamepad.enabled", false);>>"%1"
 echo user_pref("dom.block_download_insecure", false);>>"%1"
 echo user_pref("dom.private-attribution.submission.enabled", false);>>"%1"
 echo user_pref("dom.vr.oculus.enabled", false);>>"%1"
 echo user_pref("dom.vr.openvr.enabled", false);>>"%1"
 echo user_pref("dom.webaudio.enabled", false);>>"%1"
 echo user_pref("dom.enable_performance", false);>>"%1"
 echo user_pref("dom.enable_performance_navigation_timing", false);>>"%1"
 echo user_pref("dom.enable_performance_observer", false);>>"%1"
 echo user_pref("extensions.update.enabled", false);>>"%1"
 echo user_pref("extensions.blocklist.itemURL", "");>>"%1"
 echo user_pref("extensions.blocklist.detailsURL", "");>>"%1"
 echo user_pref("extensions.blocklist.enabled", false);>>"%1"
 echo user_pref("extensions.abuseReport.enabled", false);>>"%1"
 echo user_pref("extensions.getAddons.cache.enabled", false);>>"%1"
 echo user_pref("extensions.recommendations.privacyPolicyUrl", "");>>"%1"
 echo user_pref("extensions.recommendations.themeRecommendationUrl", "");>>"%1"
 echo user_pref("services.sync.engine.addons", false);>>"%1"
 echo user_pref("services.sync.engine.bookmarks", false);>>"%1"
 echo user_pref("services.sync.engine.history", false);>>"%1"
 echo user_pref("services.sync.engine.passwords", false);>>"%1"
 echo user_pref("services.sync.engine.prefs", false);>>"%1"
 echo user_pref("services.sync.engine.tabs", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.extensions.update.enabled", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.enabled", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.pinned", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.safebrowsing.malware.enabled", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.feeds.topsites", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.crashReports.unsubmittedCheck.autoSubmit2", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.feeds.section.highlights", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.feeds.section.topstories", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.section.highlights.includePocket", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.section.highlights.includeVisited", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.section.highlights.rows", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.section.topstories.rows", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsored", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSites", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.topSitesRows", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.privacy.userContext.newTabContainerOnLeftClick.enabled", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.safebrowsing.downloads.enabled", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);>>"%1"
 echo user_pref("services.sync.prefs.sync.browser.safebrowsing.phishing.enabled", false);>>"%1"
 echo user_pref("signon.autofillForms", false);>>"%1"
 echo user_pref("signon.generation.enabled", false);>>"%1"
 echo user_pref("signon.storeWhenAutocompleteOff", false);>>"%1"
 echo user_pref("signon.management.page.breachAlertUrl", "");>>"%1"
 echo user_pref("signon.management.page.breach-alerts.enabled", false);>>"%1"
 echo user_pref("toolkit.crashreporter.infoURL", "");>>"%1"
 echo user_pref("toolkit.datacollection.infoURL", "");>>"%1"
 echo user_pref("toolkit.startup.max_resumed_crashes", -1);>>"%1"
 echo user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);>>"%1"
 echo user_pref("toolkit.telemetry.server", "");>>"%1"
 echo user_pref("toolkit.telemetry.unified", false);>>"%1"
 echo user_pref("toolkit.telemetry.server_owner", "");>>"%1"
 echo user_pref("toolkit.telemetry.bhrPing.enabled", false);>>"%1"
 echo user_pref("toolkit.telemetry.updatePing.enabled", false);>>"%1"
 echo user_pref("toolkit.telemetry.newProfilePing.enabled", false);>>"%1"
 echo user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);>>"%1"
 echo user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);>>"%1"
 echo user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);>>"%1"
 echo user_pref("privacy.history.custom", true);>>"%1"
 echo user_pref("privacy.firstparty.isolate", true);>>"%1"
 echo user_pref("privacy.trackingprotection.enabled", true);>>"%1"
 echo user_pref("privacy.firstparty.isolate.use_site", true);>>"%1"
 echo user_pref("privacy.clearOnShutdown.offlineApps", true);>>"%1"
 echo user_pref("privacy.sanitize.sanitizeOnShutdown", true);>>"%1"
 echo user_pref("privacy.clearOnShutdown.siteSettings", true);>>"%1"
 echo user_pref("privacy.firstparty.isolate.block_post_message", true);>>"%1"
 echo user_pref("security.OCSP.enabled", 0);>>"%1"
 echo user_pref("security.app_menu.recordEventTelemetry", false);>>"%1"
 echo user_pref("security.certerrors.recordEventTelemetry", false);>>"%1"
 echo user_pref("security.protectionspopup.recordEventTelemetry", false);>>"%1"
 echo user_pref("datareporting.policy.firstRunURL", "");>>"%1"
 echo user_pref("datareporting.healthreport.infoURL", "");>>"%1"
 echo user_pref("datareporting.policy.firstRunTime", "1451245397413");>>"%1"
 echo user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);>>"%1"
 echo user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1451245408110");>>"%1"
 echo user_pref("media.cache_size", 0);>>"%1"
 echo user_pref("media.cache_size.cellular", 0);>>"%1"
 echo user_pref("media.navigator.enabled", false);>>"%1"
 echo user_pref("media.video_stats.enabled", false);>>"%1"
 echo user_pref("media.peerconnection.enabled", false);>>"%1"
 echo user_pref("media.peerconnection.enabled", false);>>"%1"
 echo user_pref("media.peerconnection.ice.tcp", false);>>"%1"
 echo user_pref("media.peerconnection.ice.no_host", true);>>"%1"
 echo user_pref("media.peerconnection.turn.disable", true);>>"%1"
 echo user_pref("media.peerconnection.identity.timeout", 1);>>"%1"
 echo user_pref("media.peerconnection.use_document_iceservers", false);>>"%1"
 echo user_pref("media.peerconnection.ice.default_address_only", true);>>"%1"
 echo user_pref("media.peerconnection.default_iceservers", "[127.0.0.1]");>>"%1"
 echo user_pref("network.prefetch-next", false);>>"%1"
 echo user_pref("network.dns.disableIPv6", true);>>"%1"
 echo user_pref("network.predictor.enabled", false);>>"%1"
 echo user_pref("network.cookie.cookieBehavior", 1);>>"%1"
 echo user_pref("network.proxy.socks_remote_dns", true);>>"%1"
 echo user_pref("network.http.referer.XOriginPolicy", 1);>>"%1"
 echo user_pref("network.http.referer.trimmingPolicy", 1);>>"%1"
 echo user_pref("network.http.speculative-parallel-limit", 0);>>"%1"
 echo user_pref("network.connectivity-service.enabled", false);>>"%1"
 echo user_pref("network.http.referer.XOriginTrimmingPolicy", 1);>>"%1"
 echo user_pref("network.proxy.no_proxies_on", "localhost, 127.0.0.1");>>"%1"
 echo user_pref("webgl.disabled", true);>>"%1"
 echo user_pref("webgl.min_capability_mode", true);>>"%1"
 echo user_pref("webgl.enable-debug-renderer-info", false);>>"%1"
 echo user_pref("general.autoScroll", false);>>"%1"
 echo user_pref("general.smoothScroll", false);>>"%1"
 echo user_pref("identity.sendtabpromo.url", "");>>"%1"
 echo user_pref("identity.fxaccounts.pairing.enabled", false);>>"%1"
 echo user_pref("identity.fxaccounts.toolbar.enabled", false);>>"%1"
 echo user_pref("pdfjs.migrationVersion", 2);>>"%1"
 echo user_pref("pdfjs.previousHandler.preferredAction", 2);>>"%1"
 echo user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);>>"%1"
 echo user_pref("permissions.default.camera", 2);>>"%1"
 echo user_pref("permissions.default.microphone", 2);>>"%1"
 echo user_pref("permissions.default.xr", 2);>>"%1"
 echo user_pref("webextensions.storage.sync.serverURL", "");>>"%1"
 echo user_pref("webextensions.storage.sync.enabled", false);>>"%1"
 echo user_pref("xpinstall.whitelist.required", false);>>"%1"
 echo user_pref("xpinstall.signatures.required", false);>>"%1"
 echo user_pref("devtools.remote.adb.extensionURL", "");>>"%1"
 echo user_pref("devtools.performance.recording.ui-base-url", "");>>"%1"
 echo user_pref("geo.provider.network.url", "");>>"%1"
 echo user_pref("beacon.enabled", false);>>"%1"
 echo user_pref("breakpad.reportURL", "");>>"%1"
 echo user_pref("device.sensors.enabled", false);>>"%1"
 echo user_pref("gfx.offscreencanvas.enabled", false);>>"%1"
 echo user_pref("reader.parse-on-load.enabled", false);>>"%1"
 echo user_pref("ui.use_standins_for_native_colors", true);>>"%1"
 echo user_pref("webchannel.allowObject.urlWhitelist", "");>>"%1"
exit /b

:create_userChrome
 echo /*** Proton Tabs Tweaks ***/>"%1"
 echo.>>"%1"
 echo /* Adjust tab corner shape, optionally remove space below tabs */>>"%1"
 echo.>>"%1"
 REM Uncomment the line below by removing // chars
 REM if you want to hide unified extensions button
 echo // #unified-extensions-button { display: none; }>>"%1"
 echo.>>"%1"
 echo #tabbrowser-tabs {>>"%1"
 echo     --user-tab-rounding: 6px;>>"%1"
 echo }>>"%1"
 echo.>>"%1"
 echo .tab-background {>>"%1"
 echo     border-radius: var(--user-tab-rounding) var(--user-tab-rounding) 0px 0px !important;>>"%1"
 echo     margin-block: 1px 0 !important;>>"%1"
 echo }>>"%1"
 echo #scrollbutton-up, #scrollbutton-down {>>"%1"
 echo     border-top-width: 1px !important;>>"%1"
 echo     border-bottom-width: 0 !important;>>"%1"
 echo }>>"%1"
 echo /* Container color bar visibility */>>"%1"
 echo .tabbrowser-tab[usercontextid] ^> .tab-stack ^> .tab-background ^> .tab-context-line {>>"%1"
 echo     margin: 0px max(calc(var(--user-tab-rounding) - 3px), 0px) !important;>>"%1"
 echo }>>"%1"
exit /b
