@echo off
:: choco
pwsh -CommandWithArgs "choco install apkshellext choco-cleaner cyotek-webcopy dotnet-8.0-desktopruntime dotnet-8.0-runtime exiftool hashtab hugo jcpicker privaxy python312 runinbash vcredist140 ubisoft-connect rustrover visualstudio2022community choco-protocol-support docker -y"
:: imageglass
:: --ignore-checksums"

:: scoop
pwsh -CommandWithArgs "scoop install git"
pwsh -CommandWithArgs "scoop bucket add games"
pwsh -CommandWithArgs "scoop bucket add nonportable"
pwsh -CommandWithArgs "scoop bucket add extras"
pwsh -CommandWithArgs "scoop bucket add sysinternals"
pwsh -CommandWithArgs "scoop bucket add versions"
pwsh -CommandWithArgs "scoop install adb"
pwsh -CommandWithArgs "scoop install vivaldi"
pwsh -CommandWithArgs "scoop install apktool"
pwsh -CommandWithArgs "scoop install cacert"
pwsh -CommandWithArgs "scoop install vscode"
pwsh -CommandWithArgs "scoop install cmake"
pwsh -CommandWithArgs "scoop install copyq"
pwsh -CommandWithArgs "scoop install cowsay"
pwsh -CommandWithArgs "scoop install privacy.sexy"
pwsh -CommandWithArgs "scoop install handbrake"
pwsh -CommandWithArgs "scoop install cpufetch"
pwsh -CommandWithArgs "scoop install sysinternals/process-explorer"
pwsh -CommandWithArgs "scoop install cygwin"
pwsh -CommandWithArgs "scoop install dark"
pwsh -CommandWithArgs "scoop install devd"
pwsh -CommandWithArgs "scoop install dnspyex"
pwsh -CommandWithArgs "scoop install windows-terminal"
pwsh -CommandWithArgs "scoop install DS4Windows"
pwsh -CommandWithArgs "scoop install fastfetch"
pwsh -CommandWithArgs "scoop install ffmpeg"
pwsh -CommandWithArgs "scoop install github"
pwsh -CommandWithArgs "scoop install goggalaxy"
pwsh -CommandWithArgs "scoop install gpg"
pwsh -CommandWithArgs "scoop install epic-games-launcher"
pwsh -CommandWithArgs "scoop install fastfetch"
pwsh -CommandWithArgs "scoop install grep"
pwsh -CommandWithArgs "scoop install hashcheck"
pwsh -CommandWithArgs "scoop install obsidian"
pwsh -CommandWithArgs "scoop install nilesoft-shell"
pwsh -CommandWithArgs "scoop install heroic-games-launcher"
pwsh -CommandWithArgs "scoop install insomnia"
pwsh -CommandWithArgs "scoop install jcpicker"
pwsh -CommandWithArgs "scoop install kryptor"
pwsh -CommandWithArgs "scoop install extras/powertoys"
pwsh -CommandWithArgs "scoop install masscode"
pwsh -CommandWithArgs "scoop install mc"
pwsh -CommandWithArgs "scoop install micro"
pwsh -CommandWithArgs "scoop install mingw"
pwsh -CommandWithArgs "scoop install minisign"
pwsh -CommandWithArgs "scoop install nextcloud"
pwsh -CommandWithArgs "scoop install nmap"
pwsh -CommandWithArgs "scoop install notion"
pwsh -CommandWithArgs "scoop install oh-my-posh"
pwsh -CommandWithArgs "scoop install painter"
pwsh -CommandWithArgs "scoop install pycharm"
pwsh -CommandWithArgs "scoop install resource-hacker"
pwsh -CommandWithArgs "scoop install Responsively"
pwsh -CommandWithArgs "scoop install sandboxie-plus-np"
pwsh -CommandWithArgs "scoop install screentogif"
pwsh -CommandWithArgs "scoop install simplenote"
pwsh -CommandWithArgs "scoop install SQLiteStudio"
pwsh -CommandWithArgs "scoop install staxrip"
pwsh -CommandWithArgs "scoop install steam"
pwsh -CommandWithArgs "scoop install steam-achievement-manager"
pwsh -CommandWithArgs "scoop install ttyd"
pwsh -CommandWithArgs "scoop install ventoy"
pwsh -CommandWithArgs "scoop install vhs"
pwsh -CommandWithArgs "scoop install wget"
pwsh -CommandWithArgs "scoop install windhawk"
pwsh -CommandWithArgs "scoop install z"
pause
pwsh -CommandWithArgs "scoop install scoop-completion"